In [3]:
import pandas as pd
import psycopg2
import requests
import json

In [4]:
# Get data
response = requests.get("https://data.ct.gov/resource/ngch-56tr.json")

In [5]:
response_json = response.json()

In [24]:
# Save data in .txt file in order to not hit the endpoint repeatedly
with open("data.txt", 'w') as file:
    json.dump(response_json, file)

In [25]:
# Access text file
with open("data.txt", 'r') as my_file:
    data = json.load(my_file)

In [47]:
# Store businesses in a list
businesses = []
for business in data:
    business_info = [
        business.get('credentialid'),
        business.get('name'),
        business.get('fullcredentialcode'),
        business.get('credentialtype'),
        business.get('credentialnumber'),
        business.get('credential'),
        business.get('status'),
        business.get('statusreason'),
        business.get('active'),
        business.get('issuedate'),
        business.get('effectivedate'),
        business.get('address'),
        business.get('city'),
        business.get('state'),
        business.get('zip'),
        business.get('recordrefreshedon')
    ]

    businesses.append(business_info)

In [50]:
df = pd.DataFrame(data=businesses, columns=['credentialid', 'name', 'fullcredentialcode', 'credentialtype', 'credentialnumber', 'credential', 'status', 'statusreason', 'active', 'issuedate', 'effectivedate', 'address', 'city', 'state', 'zip', 'recordrefreshedon'])

In [52]:
df.head()

,credentialid,name,fullcredentialcode,credentialtype,credentialnumber,credential,status,statusreason,active,issuedate,effectivedate,address,city,state,zip,recordrefreshedon
0,10,SEMYON RODKIN,PEN.0018966,PEN,18966,PROFESSIONAL ENGINEER,INACTIVE,FAILED TO RENEW,0,1995-03-13T00:00:00.000,2007-02-01T00:00:00.000,214 WEST 29TH ST,NEW YORK,NY,10001,2009-06-23T00:00:00.000
1,100,RAILROAD SALVAGE OF CT INC,PME.0003731,PME,3731,NON LEGEND DRUG PERMIT,INACTIVE,None,0,None,None,70 BRITANNIA ST,MERIDEN,CT,06450,2004-04-23T00:00:00.000
2,1000,ROBERT MCMAHON JR,RCG.0000413,RCG,413,CERTIFIED GENERAL REAL ESTATE APPRAISER,INACTIVE,None,0,None,1995-05-01T00:00:00.000,40 Birchwood Heights Road,Storrs,CT,06268,2009-02-05T00:00:00.000
3,10000,CHARLES L DAVENPORT,HIC.0512350,HIC,512350,HOME IMPROVEMENT CONTRACTOR,INACTIVE,EXPIRED MORE THAN 3 YEARS - MUST REAPPLY,0,None,2005-12-01T00:00:00.000,34 SHERRY DR,SOUTHINGTON,CT,06489,2018-08-16T00:00:00.000
4,100000,ROBERT C HALL,ELC.0012234-E2,ELC,12234,ELECTRICAL UNLIMITED JOURNEYPERSON,INACTIVE,None,0,None,None,84 BUDDINGTON RD #4,GROTON,CT,06340,2004-04-23T00:00:00.000